on:
  workflow_dispatch:  
  push:
    branches: [main]
    paths:
      - '**.md'

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: tcort/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
